### ISSUE TITLE
Question about MQTT server

### ISSUE THREAD

**Issue by Verbalinsurection** [albertogeniola/meross_pair#7]
Hi,
First: Congrats for your work ! 

I've tried to pair MSS310 plug to my MQTT broker (https://github.com/home-assistant/addons/tree/master/mosquitto). The broker works fine, I'm using it for my DIY energy meter and other things.
I'm using config like this :
```
logins:
  - username: mqtt
    password: imasuperpassword
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
anonymous: true
```

When I try to pair on port 8883, all the time the power plug still flashing and no push to mqtt but Wifi is ok for a short time (see in log from the router).
Something with the username / password ?

I've tried to connect to the broker using MQTT-Explorer :
- When I set username and password, works flawlessly
- When I don't set username and password, works one in five
So I think it's the same for MSS310 with no passing any credential. Its seems that user is the mac adress and password a mix with md5 of mac and other things ? 
Or simply, the mqtt broker addon have issue with anonymous connection and I have to install another one ? (yeah, I see you're in development of addon to deal with that, but I'm a hard tryer :) )

If you have any idea, thank you
